version: '3.8'

services:
    fastapi:
        container_name: fastapi
        build: ./fastapi
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
            - 8080:8000
        volumes:
            - ./fastapi:/app

    zookeeper:
        hostname: zookeeper
        container_name: zookeeper
        image: confluentinc/cp-zookeeper
        ports:
            - 2181:2181
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181

    kafka:
        hostname: kafka
        container_name: kafka
        image: confluentinc/cp-kafka
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_PRODUCER_MAX_REQUEST_SIZE: 20970000
            KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES: 20970000
            KAFKA_REPLICA_FETCH_MAX_BYTES: 20970000
            KAFKA_MESSAGE_MAX_BYTES: 20970000
        depends_on:
            - zookeeper

    schema-registry:
        container_name: schema-registry
        image: confluentinc/cp-schema-registry
        ports:
            - 8081:8081
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
            SCHEMA_REGISTRY_DEBUG: 'true'
        depends_on:
            - kafka
            - zookeeper

    connect:
        hostname: connect
        container_name: connect
        build: ./connect
        ports:
            - 8083:8083
        env_file:
            -   .env
        volumes:
            - ./connect:/connect
            - ./connect/jars:/jars

    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - 27017:27017
        command: [ "mongod", "--auth" ]
        environment:
            MONGO_ADMIN: ${MONGO_ADMIN}
            MONGO_USER: ${MONGO_USER}
        volumes:
            - ./mongo/mongo_init.sh:/usr/local/bin/mongo_init.sh
